// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travely.Models;

public partial class TblHotelImage
{
    public int ImageId { get; set; }

    public int HotelId { get; set; }

    public string ImageUrl { get; set; }

    public virtual TblHotel Hotel { get; set; }
}